src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/adapter/feign/data/AdminRequest.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/adapter/feign/data/StatusRequest.kt

Jira: [CID-1931](https://leanix.atlassian.net/browse/CID-1931)
[CID-1931]: https://leanix.atlassian.net/browse/CID-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CID-1931] Setting integrationName = gitlab-enterprise-connector in AdminRequest and StatusRequest

---

src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/GitlabFeignClientProvider.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/BaseConnectorService.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/InitialStateService.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/ValidationService.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/adapter/feign/FeignLogProvider.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/adapter/feign/LoggingClient.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/adapter/feign/data/IntegrationConfigLogRequest.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/application/LoggingService.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/domain/IntegrationConfigLog.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/domain/LogProvider.kt
src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/InitialStateServiceTest.kt
src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/ValidationServiceTest.kt
src/test/resources/mappings/gitlab-get-groups-rest.json
src/test/resources/mappings/gitlab-get-user.json

Jira: [CID-1894](https://leanix.atlassian.net/browse/CID-1894)
Doing `POST /logs/integration-config` when organization name invalid
[CID-1894]: https://leanix.atlassian.net/browse/CID-1894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CID-1894][CID-1955] Adding Integration Config logging for invalid orgName

---

src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/VsmClient.kt

CID-1970: Fix heartbeat endpoint

---

README.md

- added documentation to outline the early access functionality

feature/CID-2004 - added early access documentation

---

README.md

- fixed some styling in the documentation

feature/CID-2004 Documentation style fixes

---

README.md

- added a explanation around the support of Group Access Tokens

feature/CID-2028 - add explanation on group access tokens

---

build.gradle.kts

**Features:** 
- Optional webhook support
- Scheduled run every day at 4 AM

CID-2028 Releases version v1.1.0

---

README.md

- extended README to indicate support for GitLab Releases

feature/CID-2018 - add support for releases

---

build.gradle.kts

Bug fix:
- Validates GitLab Groups case-insensitive

CID-2047 Validates GitLab Groups case-insensitive

---

src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/graphql/GitlabGraphqlProvider.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/WebhookConsumerService.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/domain/GitlabProvider.kt
src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/InitialStateServiceTest.kt
src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/WebhookConsumerServiceImplTest.kt

Jira: [CID-2062](https://leanix.atlassian.net/browse/CID-2062)
[CID-2062]: https://leanix.atlassian.net/browse/CID-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Using `configuration.orgName` for `repo.fullPath` for `serviceRequest.orgName` 

[CID-2062] Fixing sources dropdown items

---

build.gradle.kts

Upgrading gradle version v1.2.1

Upgrading gradle version v1.2.1

---

src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/BaseConnectorService.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/ValidationService.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/adapter/feign/data/IntegrationConfigLogRequest.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/logs/domain/IntegrationConfigLog.kt
src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/ValidationServiceTest.kt

Send logs when the broker validates the customer assignment

CID-2037: Add save integration logs when the validation is successful

---

docs/gitlab-enterprise-connector.md

Update documentation on Limitations on Running Multiple Instances of GitLab Broker

CID-1976: Update documentation on Limitations on running multiple instances

---

src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/AssignmentService.kt

Update log for when failing to retrieve assignment

CID-1976: Update log for failing to retrieve assignment

---

src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/GitlabClient.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/GitlabClientProvider.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/GitlabFeignClientProvider.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/data/GitlabVersionResponse.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/application/InitialStateService.kt
src/main/kotlin/net/leanix/vsm/gitlab/broker/shared/exception/VsmException.kt
src/test/kotlin/net/leanix/vsm/gitlab/broker/connector/application/InitialStateServiceTest.kt

if the used gitlab version is less than the minimum supported version **15**, Send status logs and exit gracefully

[CID-2060] Gracefully handle unsupported versions

---

build.gradle.kts

Upgrade org.springframework.boot" to version "3.1.5"

CID-2097: Fix Snyk vulnerabilities

---

src/main/kotlin/net/leanix/vsm/gitlab/broker/connector/adapter/feign/GitlabClient.kt
src/test/resources/mappings/gitlab-get-groups-rest.json

Please explain here the changes you made in this PR.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Manual test
- [x ] 🚨 No tests Deployed
- [x ] My code follows the style guidelines
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] Any dependent changes have been merged and published in downstream modules
- [x ] I have made corresponding changes to the documentation (README.md)
- [x ] My commit message clearly reflects the changes made
- [ x] Assigned the appropriate labels (version, PR type, etc.)

CID-2047 Get top level groups only

---

build.gradle.kts

Please explain here the changes you made in this PR.

Release version 1.3.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/gradle-build.yml
CONTRIBUTING.md
README.md
SECURITY.md

Validate contribution processes by external community for our Open Source projects
This PR includes:
- Issue template for Bug Issue, Feature Request Issue.
- Security Policy template.
- A guide on how to contribute

[CID-1624] Validate contribution process

---

build.gradle.kts

Upgrading Spring boot version to 3.1.6 to address security vulnerabilities.
Tested by running integration and unit tests

CID-2182 Upgrade Spring boot version to 3.1.6

---

build.gradle.kts

1. Updates Dockerfile
2. Upgrades gradle
3. Upgrades dependencies to address known vulnerabilities

Release v1.3.1
